using System.Linq;
using Microsoft.CodeAnalysis;

namespace Cat.Network.Generator;

internal static class NetworkEntityPropertiesGenerator {
	public static void Generate(SourceProductionContext context, NetworkEntityTypeModel model) {
		context.AddSource($"{model.HintName}.g.cs", GenerateSource(model));
	}

	private static string GenerateSource(NetworkEntityTypeModel model) {
		return string.Format(
			SourceTemplate,
			Namespace(model),
			model.Accessibility,
			model.TypeName,
			Properties(model),
			PartialProperties(model));
	}

	private static string Namespace(NetworkEntityTypeModel model) {
		return string.IsNullOrWhiteSpace(model.Namespace)
			? string.Empty
			: string.Format(NamespaceTemplate, model.Namespace);
	}

	private static string Properties(NetworkEntityTypeModel model) {
		return string.Format(
			PropertiesTemplate,
			model.BaseTypeName,
			PropertyInfoEntries(model));
	}

	private static string PropertyInfoEntries(NetworkEntityTypeModel model) {
		return string.Join(
			",\n",
			model.Properties.Select((property, index) => string.Format(
				PropertyInfoEntryTemplate,
				model.BaseTypeName,
				index,
				property.Name)));
	}

	private static string PartialProperties(NetworkEntityTypeModel model) {
		return string.Join(
			"\n\n",
			model.Properties.Select(PartialProperty));
	}

	private static string PartialProperty(NetworkPropertyModel property) {
		return string.Format(
			PartialPropertyTemplate,
			property.Accessibility,
			property.TypeName,
			property.Name,
			property.GetterAccessibility,
			property.SetterAccessibility);
	}

	private const string SourceTemplate = """
	                                      // <auto-generated/>
	                                      #pragma warning disable CS0628
	                                      {0}
	                                      {1} partial class {2} : global::Cat.Network.IPartiallySerializable
	                                      {{
	                                      	// {2}
	                                      {3}

	                                      {4}
	                                      }}
	                                      """;

	private const string NamespaceTemplate = """

	                                         namespace {0};

	                                         """;

	private const string PropertiesTemplate = """

	                                          	protected static new global::System.Collections.Immutable.ImmutableArray<global::Cat.Network.NetworkPropertyInfo> Properties {{ get; }} = [
	                                          		..{0}.Properties,
	                                           {1}
	                                          	];

	                                          	global::System.Collections.Immutable.ImmutableArray<global::Cat.Network.NetworkPropertyInfo> global::Cat.Network.IPartiallySerializable.Properties => Properties;
	                                          """;

	private const string PropertyInfoEntryTemplate = """
	                                                 		new global::Cat.Network.NetworkPropertyInfo {{
	                                                 			Index = {0}.Properties.Length + {1},
	                                                 			Name = nameof({2}),
	                                                 			EncodedName = global::System.Collections.Immutable.ImmutableArray.Create(global::System.Text.Encoding.UTF8.GetBytes(nameof({2})))
	                                                 		}}
	                                                 """;

	private const string PartialPropertyTemplate = """
	                                               	{0} partial {1} {2}
	                                               	{{
	                                               		{3}get => field;
	                                               		{4}set => field = value;
	                                               	}}
	                                               """;
}
