using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Cat.Network.Generator;

internal static class NetworkObjectPropertiesGenerator {
	public static void Generate(SourceProductionContext context, NetworkObjectTypeModel model) {
		context.AddSource($"{model.HintName}.g.cs", GenerateSource(model));
	}

	private static string GenerateSource(NetworkObjectTypeModel model) {
		string source = string.Format(
			SourceTemplate,
			Namespace(model),
			model.TypeId,
			model.SerializerTypeName,
			model.TypeName,
			Properties(model),
			PartialProperties(model),
			InitializeMembers(model));

		return SyntaxFactory.ParseCompilationUnit(source).NormalizeWhitespace().ToFullString();
	}

	private static string Namespace(NetworkObjectTypeModel model) {
		return string.IsNullOrWhiteSpace(model.Namespace)
			? string.Empty
			: string.Format(NamespaceTemplate, model.Namespace);
	}

	private static string Properties(NetworkObjectTypeModel model) {
		return string.Format(
			PropertiesTemplate,
			model.HasBaseProperties ? "new " : string.Empty,
			InheritedProperties(model),
			PropertyInfoEntries(model));
	}

	private static string InheritedProperties(NetworkObjectTypeModel model) {
		return model.HasBaseProperties
			? string.Format(InheritedPropertiesTemplate, model.BaseTypeName)
			: string.Empty;
	}

	private static string PropertyInfoEntries(NetworkObjectTypeModel model) {
		IEnumerable<(string Name, int PropertyIndex)> members = model.DeclaredProperties
			.Select(static property => (property.Name, property.PropertyIndex))
			.Concat(model.DeclaredCollections.Select(static collection => (collection.Name, collection.PropertyIndex)))
			.OrderBy(static member => member.PropertyIndex);

		return string.Join(
			",\n",
			members.Select(member => string.Format(
				PropertyInfoEntryTemplate,
				member.PropertyIndex,
				member.Name)));
	}

	private static string PartialProperties(NetworkObjectTypeModel model) {
		return string.Join(
			"\n\n",
			model.DeclaredProperties.Select(PartialProperty).Concat(model.DeclaredCollections.Select(CollectionPartialProperty)));
	}

	private static string InitializeMembers(NetworkObjectTypeModel model) {
		string collectionInitializers = string.Join(
			"\n",
			model.Collections
				.OrderBy(static collection => collection.PropertyIndex)
				.Select(CollectionInitializer));

		return string.Format(
			InitializeMembersTemplate,
			model.Namespace == "Cat.Network" ? "INetworkObject" : "global::Cat.Network.INetworkObject",
			collectionInitializers);
	}

	private static string PartialProperty(NetworkPropertyModel property) {
		if (property.SerializationKind == NetworkPropertySerializationKind.NetworkObject) {
			return string.Format(
				NetworkObjectPartialPropertyTemplate,
				property.Accessibility,
				property.TypeName,
				property.Name,
				property.GetterAccessibility,
				property.SetterAccessibility,
				property.PropertyIndex);
		}

		return string.Format(
			PartialPropertyTemplate,
			property.Accessibility,
			property.TypeName,
			property.Name,
			property.GetterAccessibility,
			property.SetterAccessibility,
			property.PropertyIndex);
	}

	private static string CollectionPartialProperty(NetworkCollectionModel collection) {
		return string.Format(
			CollectionPartialPropertyTemplate,
			collection.TypeName,
			collection.BackingFieldName,
			collection.Accessibility,
			collection.Name,
			collection.GetterAccessibility);
	}

	private static string CollectionInitializer(NetworkCollectionModel collection) {
		string collectionType = collection.IsNetworkObjectItem
			? $"global::Cat.Network.NetworkObjectList<{collection.RuntimeItemTypeName}>"
			: $"global::Cat.Network.NetworkValueList<{collection.ItemTypeName}>";

		return $"{collection.BackingFieldName} = new {collectionType}(this, {collection.PropertyIndex});";
	}

	private const string SourceTemplate = """
	                                      // <auto-generated/>
	                                      #nullable enable
	                                      #pragma warning disable CS0628
	                                      {0}
	                                      [global::Cat.Network.NetworkObjectTypeId("{1}")]
	                                      [global::Cat.Network.NetworkObjectSerializerAttribute<{2}>]
	                                      partial class {3} : global::Cat.Network.INetworkObject
	                                      {{
	                                      {4}

	                                      {5}

	                                      {6}
	                                      }}
	                                      """;

	private const string NamespaceTemplate = """

	                                         namespace {0};

	                                         """;

	private const string PropertiesTemplate = """

	                                          	protected static {0}global::System.Collections.Immutable.ImmutableArray<global::Cat.Network.NetworkPropertyInfo> Properties {{ get; }} = [
	                                           {1}
	                                           {2}
	                                          	];
	                                          """;

	private const string InheritedPropertiesTemplate = """
	                                          		..{0}.Properties,
	                                          """;

	private const string PropertyInfoEntryTemplate = """
	                                                 		new global::Cat.Network.NetworkPropertyInfo {{
	                                                 			Index = {0},
	                                                 			Name = nameof({1}),
	                                                 			EncodedName = global::System.Collections.Immutable.ImmutableArray.Create(global::System.Text.Encoding.UTF8.GetBytes(nameof({1})))
	                                                 		}}
	                                                 """;

	private const string PartialPropertyTemplate = """
	                                               	{0} partial {1} {2}
	                                               	{{
	                                               		{3}get => field;
	                                               		{4}set
	                                               		{{
	                                               			{1} oldValue = field;
	                                               			if (global::System.Collections.Generic.EqualityComparer<{1}>.Default.Equals(oldValue, value))
	                                               			{{
	                                               				return;
	                                               			}}
	                                               			field = value;
	                                               			global::Cat.Network.INetworkObject current = this;
	                                               			current.PropertyStates[{5}] |= global::Cat.Network.NetworkPropertyState.Replaced;
	                                               			while (current.Parent is global::Cat.Network.NetworkObject parent)
	                                               			{{
	                                               				global::Cat.Network.INetworkObject parentObject = parent;
	                                               				parentObject.PropertyStates[current.PropertyIndex] |= global::Cat.Network.NetworkPropertyState.Modified;
	                                               				current = parentObject;
	                                               			}}
	                                               		}}
	                                               	}}
	                                               """;

	private const string NetworkObjectPartialPropertyTemplate = """
	                                                     	{0} partial {1} {2}
	                                                     	{{
	                                                     		{3}get => field;
	                                                     		{4}set
	                                                     		{{
	                                                     			{1} oldValue = field;
	                                                     			int propertyIndex = {5};
	                                                     			if (global::System.Object.ReferenceEquals(oldValue, value))
	                                                     			{{
	                                                     				return;
	                                                     			}}
	                                                     			if (value is not null)
	                                                     			{{
	                                                     				global::Cat.Network.INetworkObject networkValue = value;
	                                                     				if (networkValue.Parent is not null && (!global::System.Object.ReferenceEquals(networkValue.Parent, this) || networkValue.PropertyIndex != propertyIndex))
	                                                     				{{
	                                                     					throw new global::System.InvalidOperationException("NetworkObjects may only occupy one networked property at a time.");
	                                                     				}}
	                                                     			}}
	                                                     			field = value;
	                                                     			if (oldValue is not null)
	                                                     			{{
	                                                     				global::Cat.Network.INetworkObject oldNetworkValue = oldValue;
	                                                     				oldNetworkValue.Parent = null;
	                                                     				oldNetworkValue.PropertyIndex = -1;
	                                                     			}}
	                                                     			if (value is not null)
	                                                     			{{
	                                                     				global::Cat.Network.INetworkObject attachedValue = value;
	                                                     				attachedValue.Parent = this;
	                                                     				attachedValue.PropertyIndex = propertyIndex;
	                                                     			}}
	                                                     			global::Cat.Network.INetworkObject current = this;
	                                                     			current.PropertyStates[propertyIndex] |= global::Cat.Network.NetworkPropertyState.Replaced;
	                                                     			while (current.Parent is global::Cat.Network.NetworkObject parent)
	                                                     			{{
	                                                     				global::Cat.Network.INetworkObject parentObject = parent;
	                                                     				parentObject.PropertyStates[current.PropertyIndex] |= global::Cat.Network.NetworkPropertyState.Modified;
	                                                     				current = parentObject;
	                                                     			}}
	                                                     		}}
	                                                     	}}
	                                                     """;

	private const string CollectionPartialPropertyTemplate = """
	                                                   	private protected {0} {1} = null!;
	                                                   	{2} partial {0} {3}
	                                                   	{{
	                                                   		{4}get => {1};
	                                                   	}}
	                                                   """;

	private const string InitializeMembersTemplate = """

	                                         	void {0}.Initialize()
	                                         	{{
	                                         		((global::Cat.Network.INetworkObject)this).PropertyStates = new global::Cat.Network.NetworkPropertyState[Properties.Length];
	                                         		{1}
	                                         	}}
	                                         """;
}
