using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Cat.Network.Generator;

internal static class NetworkObjectPropertiesGenerator {
	public static void Generate(SourceProductionContext context, NetworkObjectTypeModel model) {
		context.AddSource($"{model.HintName}.g.cs", GenerateSource(model));
	}

	private static string GenerateSource(NetworkObjectTypeModel model) {
		string source = string.Format(
			SourceTemplate,
			Namespace(model),
			model.TypeId,
			model.SerializerTypeName,
			model.Accessibility,
			model.TypeName,
			ClassInheritance(model),
			Properties(model),
			PartialProperties(model),
			InitializeMembers(model));

		return SyntaxFactory.ParseCompilationUnit(source).NormalizeWhitespace().ToFullString();
	}

	private static string Namespace(NetworkObjectTypeModel model) {
		return string.IsNullOrWhiteSpace(model.Namespace)
			? string.Empty
			: string.Format(NamespaceTemplate, model.Namespace);
	}

	private static string ClassInheritance(NetworkObjectTypeModel model) {
		return model.TypeName == "NetworkObject" && model.Namespace == "Cat.Network"
			? " : global::Cat.Network.INetworkObject"
			: $" : {model.BaseTypeName}, global::Cat.Network.INetworkObject";
	}

	private static string Properties(NetworkObjectTypeModel model) {
		return string.Format(
			PropertiesTemplate,
			model.HasBaseProperties ? "new " : string.Empty,
			InheritedProperties(model),
			PropertyInfoEntries(model));
	}

	private static string InheritedProperties(NetworkObjectTypeModel model) {
		return model.HasBaseProperties
			? string.Format(InheritedPropertiesTemplate, model.BaseTypeName)
			: string.Empty;
	}

	private static string PropertyInfoEntries(NetworkObjectTypeModel model) {
		return string.Join(
			",\n",
			model.DeclaredProperties.Select((property, index) => string.Format(
				PropertyInfoEntryTemplate,
				model.HasBaseProperties ? $"{model.BaseTypeName}.Properties.Length" : "0",
				index,
				property.Name)));
	}

	private static string PartialProperties(NetworkObjectTypeModel model) {
		return string.Join(
			"\n\n",
			model.DeclaredProperties.Select((property, index) => PartialProperty(model, property, index)));
	}

	private static string InitializeMembers(NetworkObjectTypeModel model) {
		return string.Format(
			InitializeMembersTemplate,
			model.Namespace == "Cat.Network" ? "INetworkObject" : "global::Cat.Network.INetworkObject");
	}

	private static string PartialProperty(NetworkObjectTypeModel model, NetworkPropertyModel property, int index) {
		if (property.SerializationKind == NetworkPropertySerializationKind.NetworkObject) {
			return string.Format(
				NetworkObjectPartialPropertyTemplate,
				property.Accessibility,
				property.TypeName,
				property.Name,
				property.GetterAccessibility,
				property.SetterAccessibility,
				model.HasBaseProperties ? $"{model.BaseTypeName}.Properties.Length + {index}" : index.ToString());
		}

		return string.Format(
			PartialPropertyTemplate,
			property.Accessibility,
			property.TypeName,
			property.Name,
			property.GetterAccessibility,
			property.SetterAccessibility);
	}

	private const string SourceTemplate = """
	                                      // <auto-generated/>
	                                      #nullable enable
	                                      #pragma warning disable CS0628
	                                      {0}
	                                      [global::Cat.Network.NetworkObjectTypeId("{1}")]
	                                      [global::Cat.Network.NetworkObjectSerializerAttribute<{2}>]
	                                      {3} partial class {4}{5}
	                                      {{
	                                      	// {4}
	                                      {6}

	                                      {7}

	                                      {8}
	                                      }}
	                                      """;

	private const string NamespaceTemplate = """

	                                         namespace {0};

	                                         """;

	private const string PropertiesTemplate = """

	                                          	protected static {0}global::System.Collections.Immutable.ImmutableArray<global::Cat.Network.NetworkPropertyInfo> Properties {{ get; }} = [
	                                           {1}
	                                           {2}
	                                          	];
	                                          """;

	private const string InheritedPropertiesTemplate = """
	                                          		..{0}.Properties,
	                                          """;

	private const string PropertyInfoEntryTemplate = """
	                                                 		new global::Cat.Network.NetworkPropertyInfo {{
	                                                 			Index = {0} + {1},
	                                                 			Name = nameof({2}),
	                                                 			EncodedName = global::System.Collections.Immutable.ImmutableArray.Create(global::System.Text.Encoding.UTF8.GetBytes(nameof({2})))
	                                                 		}}
	                                                 """;

	private const string PartialPropertyTemplate = """
	                                               	{0} partial {1} {2}
	                                               	{{
	                                               		{3}get => field;
	                                               		{4}set => field = value;
	                                               	}}
	                                               """;

	private const string NetworkObjectPartialPropertyTemplate = """
	                                                     	{0} partial {1} {2}
	                                                     	{{
	                                                     		{3}get => field;
	                                                     		{4}set
	                                                     		{{
	                                                     			{1} oldValue = field;
	                                                     			int propertyIndex = {5};
	                                                     			if (global::System.Object.ReferenceEquals(oldValue, value))
	                                                     			{{
	                                                     				return;
	                                                     			}}
	                                                     			if (value is not null)
	                                                     			{{
	                                                     				global::Cat.Network.INetworkObject networkValue = value;
	                                                     				if (networkValue.Parent is not null && (!global::System.Object.ReferenceEquals(networkValue.Parent, this) || networkValue.PropertyIndex != propertyIndex))
	                                                     				{{
	                                                     					throw new global::System.InvalidOperationException("NetworkObjects may only occupy one networked property at a time.");
	                                                     				}}
	                                                     			}}
	                                                     			field = value;
	                                                     			if (oldValue is not null)
	                                                     			{{
	                                                     				global::Cat.Network.INetworkObject oldNetworkValue = oldValue;
	                                                     				oldNetworkValue.Parent = null;
	                                                     				oldNetworkValue.PropertyIndex = -1;
	                                                     			}}
	                                                     			if (value is not null)
	                                                     			{{
	                                                     				global::Cat.Network.INetworkObject attachedValue = value;
	                                                     				attachedValue.Parent = this;
	                                                     				attachedValue.PropertyIndex = propertyIndex;
	                                                     			}}
	                                                     		}}
	                                                     	}}
	                                                     """;

	private const string InitializeMembersTemplate = """

	                                         	void {0}.Initialize()
	                                         	{{
	                                         		((global::Cat.Network.INetworkObject)this).PropertyStates = new global::Cat.Network.NetworkPropertyState[Properties.Length];
	                                         	}}
	                                         """;
}
