using Microsoft.CodeAnalysis;

namespace Cat.Network.Generator;

internal static class NetworkObjectSerializerGenerator {
	public static void Generate(SourceProductionContext context, NetworkObjectTypeModel model) {
		context.AddSource($"{model.SerializerHintName}.g.cs", GenerateSource(model));
	}

	private static string GenerateSource(NetworkObjectTypeModel model) {
		return string.Format(
			SourceTemplate,
			Namespace(model),
			model.SerializerTypeName);
	}

	private static string Namespace(NetworkObjectTypeModel model) {
		return string.IsNullOrWhiteSpace(model.Namespace)
			? string.Empty
			: string.Format(NamespaceTemplate, model.Namespace);
	}

	private const string SourceTemplate = """
	                                      // <auto-generated/>
	                                      {0}
	                                      internal sealed class {1} : global::Cat.Network.INetworkObjectSerializer
	                                      {{
	                                      	public static void Serialize() {{
	                                      	}}

	                                      	public static void Deserialize() {{
	                                      	}}
	                                      }}
	                                      """;

	private const string NamespaceTemplate = """

	                                         namespace {0};

	                                         """;
}
