using System.Text;
using Microsoft.CodeAnalysis;

namespace Cat.Network.Generator;

internal static class NetworkEntityPartialClassPath {
	public static void Generate(SourceProductionContext context, NetworkEntityTypeModel model) {
		StringBuilder source = new();

		source.AppendLine("// <auto-generated/>");
		source.AppendLine();

		if (!string.IsNullOrWhiteSpace(model.Namespace)) {
			source.Append("namespace ");
			source.Append(model.Namespace);
			source.AppendLine(";");
			source.AppendLine();
		}

		source.Append(model.Accessibility);
		source.Append(" partial class ");
		source.AppendLine(model.TypeName);
		source.AppendLine("{");
		source.Append("\t// ");
		source.AppendLine(model.TypeName);
		foreach (NetworkPropertyModel property in model.Properties) {
			source.AppendLine();
			AppendProperty(source, property);
		}
		source.AppendLine("}");

		context.AddSource($"{model.HintName}.g.cs", source.ToString());
	}

	private static void AppendProperty(StringBuilder source, NetworkPropertyModel property) {
		source.Append("\tpublic partial ");
		source.Append(property.TypeName);
		source.Append(' ');
		source.AppendLine(property.Name);
		source.AppendLine("\t{");

		if (property.HasGetter) {
			source.AppendLine("\t\tget => field;");
		}

		if (property.HasSetter) {
			source.AppendLine("\t\tset => field = value;");
		}

		source.AppendLine("\t}");
	}
}
